BASE <http://instans.org/>
PREFIX : <http:instans.org/default#>
PREFIX geo: <http://www.w3.org/2003/01/geo/wgs84_pos#>
PREFIX ssn: <http://purl.oclc.org/NET/ssnx/ssn#>
PREFIX ep: <http://www.ontologydesignpatterns.org/cp/owl/eventprocessing.owl#>
PREFIX omgeo: <http://www.ontotext.com/owlim/geo#>
PREFIX ff: <http://factforge.net/>

# Project (EPA 4): Delete information from the incoming events

# @name EPA4-Project
CONSTRUCT {  GRAPH <projected> { ?s ?p ?o } }
WHERE {  GRAPH <translated> { 
    ?event a ep:EventObject .
    ?s ?p ?o
    FILTER(?p != :locationName)
}};
