# PREFIX instans: <http://instans.org/extensions/instans#>
# PREFIX rdf:    <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
# PREFIX rdfs:   <http://www.w3.org/2000/01/rdf-schema#>
# PREFIX mf:     <http://www.w3.org/2001/sw/DataAccess/tests/test-manifest#>
# PREFIX qt:     <http://www.w3.org/2001/sw/DataAccess/tests/test-query#>
# PREFIX ut:     <http://www.w3.org/2009/sparql/tests/test-update#>
# PREFIX dawgt:  <http://www.w3.org/2001/sw/DataAccess/tests/test-dawg#>
# PREFIX sd:      <http://www.w3.org/ns/sparql-service-description#>
SELECT ?p {
       ?s ?p ?o
}
