# CONSTRUCT { ?s ?p ?o }
# WHERE {
#       GRAPH ?g { ?s ?p ?o }
# }

CONSTRUCT {
      GRAPH ?g { ?s ?p ?o }
} WHERE {
      GRAPH ?g { ?s ?p ?o }
}
;
CONSTRUCT { ?s ?p ?o }
WHERE {
      { ?s ?p ?o }
}
