PREFIX tl:<http://purl.org/NET/c4dm/timeline.owl#>
PREFIX geo:<http://www.w3.org/2003/01/geo/wgs84_pos#>
PREFIX xsd:<http://www.w3.org/2001/XMLSchema#>
PREFIX : <http://instans.org/>

#:ev0 { :sensor1 a :Thermometer; :location [ geo:lat 60.15922234475837; geo:long 24.87610729902513 ]; :timestamp 0; :reading 0 }
#:ev0 { :sensor1 a :Thermometer; :location [ geo:lat 60.15922234475837; geo:long 24.87610729902513 ]; :timestamp 0; :reading 0 }


DELETE { ?sensor :sum ?sum; :count ?count; :event ?event} 
INSERT { ?sensor :sum ?newsum; :count ?newcount; :event ?newevent }
WHERE {
      GRAPH ?newevent {
        ?sensor a :Thermometer; :timestamp ?ts; :reading ?reading .
      }
      ?sensor :sum ?sum; :count ?count; :event ?event
      FILTER(?event != ?newevent)
      BIND(?sum + ?reading AS ?newsum)
      BIND(?count + 1 AS ?newcount)
}
;
SELECT ?count ?sum WHERE { ?sensor :sum ?sum; :count ?count}
# ;
# SELECT * {
#       GRAPH ?event {
#         ?sensor # a :Thermometer; :timestamp ?ts;
# 	 :reading ?reading .
#       }
#}
