PREFIX instans: <http://instans.org/extensions/instans#>
PREFIX rdf:    <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX :       <http://www.w3.org/2009/sparql/docs/tests/data-sparql11/bind/manifest#>
PREFIX rdfs:   <http://www.w3.org/2000/01/rdf-schema#>
PREFIX mf:     <http://www.w3.org/2001/sw/DataAccess/tests/test-manifest#>
PREFIX qt:     <http://www.w3.org/2001/sw/DataAccess/tests/test-query#>
PREFIX dawgt:  <http://www.w3.org/2001/sw/DataAccess/tests/test-dawg#>
PREFIX its:    <http://instans.aalto.fi/testsuite/#>

#SELECT ?x ?label ?reqlist 
INSERT { ?x instans:iterate [ instans:list ?reqlist; instans:map_predicate mf:conformanceRequirement ] }
WHERE { ?x a mf:Manifest ;
	   rdfs:label ?label ;
	   mf:include ?reqlist
}
;
SELECT ?x ?reqlist 
WHERE {
 ?x instans:iterate [ instans:list ?reqlist; instans:map_predicate mf:conformanceRequirement ] 
}
