PREFIX instans: <http://instans.org/extensions/instans#>
PREFIX rdf:    <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX :       <http://www.w3.org/2009/sparql/docs/tests/data-sparql11/bind/manifest#>
PREFIX rdfs:   <http://www.w3.org/2000/01/rdf-schema#>
PREFIX mf:     <http://www.w3.org/2001/sw/DataAccess/tests/test-manifest#>
PREFIX qt:     <http://www.w3.org/2001/sw/DataAccess/tests/test-query#>
PREFIX dawgt:  <http://www.w3.org/2001/sw/DataAccess/tests/test-dawg#>
PREFIX its:    <http://instans.aalto.fi/testsuite/#>

# INSERT { its:work its:member ?entries }
# WHERE { ?testset rdf:type mf:Manifest ;
#        rdfs:label "BIND" ;
#        mf:entries ?entries .
# }

SELECT ?test ?name ?testtype ?queryfile ?datafile ?resultfile ?success WHERE {
#       ?test a 	       ?testtype;
       ?test a <http://www.w3.org/2001/sw/DataAccess/tests/test-manifest#NegativeSyntaxTest11> ;
             mf:name   ?name .
       ?test mf:action ?action .
       { ?action qt:query ?queryfile } UNION { BIND(?action AS ?queryfile) FILTER(strends(str(?queryfile), ".rq"))}
       { ?action qt:data ?datafile }   UNION { BIND(rdf:nil AS ?datafile) }
       { ?test mf:result ?resultfile } UNION { BIND(rdf:nil AS ?resultfile) }
       BIND(instans:execute_system(?queryfile, ?datafile, ?resultfile, rdf:nil) AS ?success)
#       BIND(true AS ?success)
}

