BASE <http://instans.org/>
PREFIX : <http://instans.org/>

# Case 1: No duplicate removal (OK)
# ===========================

# @name Both-Ways
INSERT { GRAPH <puskuri> { ?e1 :p1 ?p1 ; :p2 ?p2 } }
WHERE { ?e1 :p1 ?p1 ; :p2 ?p2 .
  ?e2 :p1 ?p2 ;
        :p2 ?p1 .
 } ;

# @name Filter-And-Output
SELECT * WHERE { GRAPH <puskuri> { ?e1 :p1 ?p1 ; :p2 ?p2 .
  # FILTER NOT EXISTS {
  #   ?e2 :p1 ?p2 ;
  #         :p2 ?p1 }
} } ;

# Vastauksia 2 (OK):
# e1,p1,p2
# _:0,<john>,<mary>
# _:1,<mary>,<john>

# Report-All tiedostossa "case1.dbg"

# Shell: ../../../../bin/instans --prefix-encoding=true -r test1.rq --report=all -t test.ttl
# Lisp: (main (format nil "-d ~A/tests/removing-two-ways --prefix-encoding=true -r test1.rq --report=all -t test.ttl" (find-instans-root-directory)))

