PREFIX :<http:instans.org/default#>
PREFIX rdf:<http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX tl:<http://purl.org/NET/c4dm/timeline.owl#>
PREFIX geo:<http://www.w3.org/2003/01/geo/wgs84_pos#>
PREFIX foaf:<http://xmlns.com/foaf/0.1/>
PREFIX event:<http://purl.org/NET/c4dm/event.owl#>
PREFIX xsd:<http://www.w3.org/2001/XMLSchema#>
PREFIX ssn:<http://purl.oclc.org/NET/ssnx/ssn#>
PREFIX ep:<http://www.ontologydesignpatterns.org/cp/owl/eventprocessing.owl#>

CONSTRUCT {
 ?event a ep:EventObject ; # Originally [] subject, but CONSTRUCT cannot generate that yet?
    ssn:Sensor ?person ;
    ep:hasEventObjectSamplingTime ?dttm ;
    geo:Point ?p .
?p geo:lat ?lat ;
    geo:long ?long .
}
# SELECT *
WHERE {
  ?event rdf:type event:Event ;
   	 event:agent ?person ;
   	 event:time ?t ;
         event:place ?p .
   ?t tl:at ?dttm .
   ?p  geo:lat ?lat ;
       geo:long ?long 
} ;

DELETE {
  ?event rdf:type event:Event ;
   	 event:agent ?person ;
   	 event:time ?t ;
         event:place ?p .
   ?t tl:at ?dttm .
   ?p  geo:lat ?lat ;
       geo:long ?long 
}
WHERE {
  ?event rdf:type event:Event ;
   	 event:agent ?person ;
   	 event:time ?t ;
         event:place ?p .
   ?t tl:at ?dttm .
   ?p  geo:lat ?lat ;
       geo:long ?long 
} ;

