PREFIX : <http://instans.org/>
PREFIX ep:<http://www.ontologydesignpatterns.org/cp/owl/eventprocessing.owl#>
PREFIX memory: <http://example.org/memory/>
PREFIX output: <http://example.org/output/>

DELETE { GRAPH memory: { :poststateful :prevHour ?prevhour; :uuid ?prevuuid } }
INSERT { GRAPH output: { ?event ep:hasEventObjectSamplingTime ?time }
         GRAPH memory: { :poststateful :prevHour ?hour; :uuid ?uuid }
}
WHERE { 
   ?event ep:hasEventObjectSamplingTime ?time .
   BIND(uuid() AS ?uuid)
   GRAPH memory: { OPTIONAL  { :poststateful :prevHour ?prevhour; :uuid ?prevuuid } }
   FILTER(!bound(?prevuuid) || ?uuid != ?prevuuid)
   BIND ( HOURS(?time) as ?hour )
};

SELECT * WHERE { GRAPH ?g { ?s ?p ?o } }
