PREFIX : <http://instans.org/>
PREFIX mem: <http://instans.org/memory/>

INSERT { GRAPH mem: { :count :value ?value } }
WHERE { :init :value ?value }
;
DELETE { :event :value ?val
         GRAPH mem: { :count :value ?sum } }
INSERT { GRAPH mem: { :count :value ?newSum } }
WHERE {
  :event :value ?val
  GRAPH mem: { :count :value ?sum }
  BIND ( ?sum + ?val AS ?newSum )
}
;
SELECT *
WHERE { GRAPH mem: { ?s ?p ?o } }
