#!/usr/bin/env awk -f
/^Rule/ {
    if (queryfile) printf "%s %s returns %s\n", type, queryfile, success;
}
/.*SPARQL-VAR \?QUERYFILE> = .*/ {
    split($5, n, ">");
    queryfile = n[1];
#    printf "\nQUERYFILE = %s\n", queryfile;
}
/.*SPARQL-VAR \?TESTTYPE> = #<RDF-IRI / {
    split($5, a, "#");
    split(a[2], t, ">");
    type = t[1];
#    printf "TYPE = %s\n", type;
}
/.*SPARQL-VAR \?PARSED_OK> = #<SPARQL-UNBOUND.*/ {
    success = "UNBOUND";
#    printf "PARSED_OK = UNBOUND\n"
}
/.*SPARQL-VAR \?PARSED_OK> = T/ {
    success = "true";
#    printf "PARSED_OK = true\n"
}
/.*SPARQL-VAR \?PARSED_OK> = NIL/ {
    success = "false";
#    printf "parse_ok = false\n"
}
END {
    if (queryfile) printf "%s %s returns %s\n", type, queryfile, success;
}
