#!/bin/sh
LOGFILE=MKHTML_LOG

msg() {
    if test "${LOGFILE}" != ""; then
	test -f ${LOGFILE} || touch ${LOGFILE}
	echo `date`: $* >> ${LOGFILE}
    fi
    echo $*
}

if test $# -eq 1 ; then
    SPARQL=$1
    OUTPUT_DIR="."
elif test $# -eq 2; then
    SPARQL=$1
    OUTPUT_DIR=$2
else
    msg "Usage: mk-html sparql [output]"
    exit 1
fi
BN=`basename $SPARQL .rq`
BN=`basename $BN .sparql`
SA=${OUTPUT_DIR}/$BN.sa
DOT=${OUTPUT_DIR}/$BN.dot
OUTPUT=${OUTPUT_DIR}/$BN.html

msg SPARQL=${SPARQL}, SA=${SA}, DOT=${DOT}, OUTPUT=${OUTPUT}
{
cat > $OUTPUT <<EOF
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML//EN">
<html>
<head>
<title></title>
</head>
<body>
<table border="1" cellspacing="0" cellpadding="4"><tr><td>
<pre>
EOF
if test `expr $SPARQL : 'http://'` -eq 7 -o `expr $SPARQL : 'https://'` -eq 8 ; then
msg "curl $SPARQL"
curl $SPARQL | sed '/</s//\&lt;/g' | sed '/>/s//\&gt;/g' >> $OUTPUT
else
cat $SPARQL | sed '/</s//\&lt;/g' | sed '/>/s//\&gt;/g' >> $OUTPUT
fi
cat >> $OUTPUT <<EOF
</pre>
</td>
<td>
<pre>
EOF
cat $SA >> $OUTPUT
cat >> $OUTPUT <<EOF
</pre>
</td>
</tr>
</table>
<hr/>
EOF
dot -Tsvg -O $DOT
cat $DOT.svg >> $OUTPUT
cat >> $OUTPUT <<EOF
<hr/>
</body>
</html>
EOF
} >> ${LOGFILE} 2>&1
