#!/bin/sh
TMP=$$_main.lisp
cat << EOF > $TMP
(with-open-file (*standard-output* "/dev/null" :direction :output
                                   :if-exists :supersede)
(asdf:load-system :instans))
(in-package #:instans)
(run-data-r2-syntax-tests)
(run-data-sparql11-syntax-tests)
EOF

sbcl --noinform --noprint --load $TMP --quit
rm -rf $TMP

