#!/bin/sh
TMP=$$_main.lisp
cat << EOF > $TMP
(with-open-file (*standard-output* "/dev/null" :direction :output
                                   :if-exists :supersede)
(asdf:load-system :instans))
(in-package #:instans)
(run-syntax1-testsuites "syntax-sparql1" "syntax-sparql2" "syntax-sparql3" "syntax-sparql4" "syntax-sparql5")
EOF

sbcl --noinform --noprint --load $TMP --quit
rm -rf $TMP

