BASE <http://instans.org/>
PREFIX : <http:instans.org/default#>
PREFIX geo: <http://www.w3.org/2003/01/geo/wgs84_pos#>
PREFIX ssn: <http://purl.oclc.org/NET/ssnx/ssn#>
PREFIX ep: <http://www.ontologydesignpatterns.org/cp/owl/eventprocessing.owl#>
PREFIX omgeo: <http://www.ontotext.com/owlim/geo#>
PREFIX ff: <http://factforge.net/>

# Stateless filter (EPA 1): Only events generated during business hours

# @name EPA1-Stateless
CONSTRUCT { GRAPH ?newgraph { ?s ?p ?o } }
WHERE { GRAPH ?g {
    FILTER ( strStarts(str(?g),concat(str(<>),"Eve")) )
    ?s ?p ?o .
    ?event ep:hasEventObjectSamplingTime ?time }
  FILTER ( ( HOURS(?time) > 8 ) && ( HOURS(?time) < 17 ) )
  BIND (IRI(concat("Poststateless-",strAfter(str(?event),str(<>)))) AS ?newgraph) } ;

#@name Cleanup-Input
# DELETE { GRAPH ?g1 { ?s ?p ?o } }
# WHERE {
#   GRAPH ?g1 {
#     FILTER ( strStarts(str(?g1),concat(str(<>),"Eve")) )
#     ?s ?p ?o .
#     ?event ep:hasEventObjectSamplingTime ?time1 }
#   FILTER EXISTS { GRAPH ?g2 {
#     FILTER ( strStarts(str(?g2),concat(str(<>),"Eve")) )
#       ?event2 ep:hasEventObjectSamplingTime ?time2 .
#       FILTER (?time1 < ?time2) } }
# };

