BASE <http://instans.org/>
PREFIX : <http:instans.org/default#>
PREFIX geo: <http://www.w3.org/2003/01/geo/wgs84_pos#>
PREFIX ssn: <http://purl.oclc.org/NET/ssnx/ssn#>
PREFIX ep: <http://www.ontologydesignpatterns.org/cp/owl/eventprocessing.owl#>
PREFIX omgeo: <http://www.ontotext.com/owlim/geo#>
PREFIX ff: <http://factforge.net/>

# Split (EPA 5): Split into separate channels using original blank nodes.

CONSTRUCT { GRAPH ?geograph {
    ?event a ep:EventObject ;
           ep:hasEventObjectSamplingTime ?time ;
           geo:Point [ geo:lat ?lat ; geo:long ?long ; ] }
  GRAPH ?sensorgraph {
    ?event a ep:EventObject ;
           ssn:Sensor ?sensor ;
           ep:hasEventObjectSamplingTime ?time } }
WHERE { GRAPH ?g { # Match incoming events
    FILTER ( strStarts(str(?g),concat(str(<>),"Eve")) )
    ?event a ep:EventObject ;
           ssn:Sensor ?sensor ;
           geo:Point [ geo:lat ?lat ; geo:long ?long ; ] ;
           ep:hasEventObjectSamplingTime ?time }
  BIND (IRI(concat("GeoEvents-",strAfter(str(?event),str(<>)))) AS ?geograph)
  BIND (IRI(concat("SensorEvents-",strAfter(str(?event),str(<>)))) AS ?sensorgraph) } ;

